server/djangoapp/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'djangoapp'
urlpatterns = [
    # route is a string contains a URL pattern
    # view refers to the view function
    # name the URL

    # path for about view
    path(route = 'about/', view = views.about, name='about'),

    # path for contact us view
    path(route = 'contact/', view = views.contact, name='contact'),

    # path for registration
    path('signup/', views.registration_request, name='registration'),
    # path for login
    path('login/', views.login_request, name='login'),
    # path for logout
    path('logout/', views.logout_request, name='logout'),

    path(route='', view=views.get_dealerships, name='index'),

    # path for dealer reviews view
    path('dealer/<int:dealer_id>/', views.get_dealer_details, name='dealer_details'),

    # path for add a review view
    path('dealer/<int:dealer_id>/add_review/', views.add_review, name='add_review')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangobackend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('djangoapp/', include('djangoapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

server/djangoapp/models.py
from django.db import models
from django.utils.timezone import now


# Create your models here.

class CarMake(models.Model):
    name = models.CharField(null= False, max_length=30, default='Audi')
    description = models.CharField(null= False, max_length=300, default='Audi cars are aight')

    def __str__(self):
        return 'Name:' + self.name + ',' + \
            'Description:' + self.description


class CarModel(models.Model):
    SEDAN = 'sedan'
    SUV = 'suv'
    WAGON = 'wagon'
    OTHERS = 'others'
    CAR_CHOICES = [(SEDAN, "Sedan"), (SUV, 'SUV'), (WAGON, 'Wagon'), (OTHERS, 'Others')]
    carmake = models.ForeignKey(CarMake, null= True, on_delete=models.CASCADE)
    name = models.CharField(null= False, max_length=30, default='Audi X8')
    dealerid = models.IntegerField(null=True)
    cartype = models.CharField(null= False, max_length=20, choices= CAR_CHOICES, default=SEDAN)
    year = models.DateField(null= True)

    def __str__(self):
        return 'Name ' + self.name
# <HINT> Create a plain Python class `CarDealer` to hold dealer data

class CarDealer:

    def __init__(self, address, city, full_name, id, lat, long, short_name, st, zip):
        # Dealer address
        self.address = address
        # Dealer city
        self.city = city
        # Dealer Full Name
        self.full_name = full_name
        # Dealer id
        self.id = id
        # Location lat
        self.lat = lat
        # Location long
        self.long = long
        # Dealer short name
        self.short_name = short_name
        # Dealer state
        self.st = st
        # Dealer zip
        self.zip = zip
        self.idx = 0

    def __str__(self):
        return "Dealer name: " + self.full_name


# <HINT> Create a plain Python class `DealerReview` to hold review data
class DealerReview:
    def __init__(self, name, dealership, review, purchase, purchase_date, car_make, car_model, car_year, sentiment):
        self.name = name
        self.dealership = dealership
        self.review = review
        self.purchase = purchase
        self.purchase_date = purchase_date
        self.car_make = car_make
        self.car_model = car_model
        self.car_year = car_year
        self.sentiment = sentiment

    def __str__(self):
        return "Review: " + self.review

server/djangoapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render, redirect
# from .models import related models
# from .restapis import related methods
from django.contrib.auth import login, logout, authenticate
from django.contrib import messages
from datetime import datetime
import logging
import json
from . import restapis
from . import models

# Get an instance of a logger
logger = logging.getLogger(__name__)


# Create your views here.


# Create an `about` view to render a static about page
def about(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/about.html', context)


# Create a `contact` view to return a static contact page
def contact(request):
    context = {}
    if request.method == 'GET':
        return render(request, 'djangoapp/contact.html', context)
# Create a `login_request` view to handle sign in request
def login_request(request):
    context = {}
    # Handles POST request
    if request.method == "POST":
        # Get username and password from request.POST dictionary
        username = request.POST['username']
        password = request.POST['psw']
        # Try to check if provide credential can be authenticated
        user = authenticate(username=username, password=password)
        if user is not None:
            # If user is valid, call login method to login current user
            login(request, user)
            return redirect('/djangoapp/')
        else:
            # If not, return to login page again
            return render(request, 'djangoapp/user_login.html', context)
    else:
        return render(request, 'djangoapp/user_login.html', context)

# Create a `logout_request` view to handle sign out request
def logout_request(request):
    # Get the user object based on session id in request
    print("Log out the user `{}`".format(request.user.username))
    # Logout user in the request
    logout(request)
    # Redirect user back to course list view
    return redirect('/djangoapp')

# Create a `registration_request` view to handle sign up request
def registration_request(request):
    context = {}
    # If it is a GET request, just render the registration page
    if request.method == 'GET':
        return render(request, 'djangoapp/registration.html', context)
    # If it is a POST request
    elif request.method == 'POST':
        # Get user information from request.POST
        username = request.POST['username']
        password = request.POST['psw']
        first_name = request.POST['firstname']
        last_name = request.POST['lastname']
        user_exist = False
        try:
            # Check if user already exists
            User.objects.get(username=username)
            user_exist = True
        except:
            # If not, simply log this is a new user
            logger.debug("{} is new user".format(username))
        # If it is a new user
        if not user_exist:
            # Create user in auth_user table
            user = User.objects.create_user(username=username, first_name=first_name, last_name=last_name,
                                            password=password)
            # Login the user and redirect to course list page
            login(request, user)
            return redirect("/djangoapp/")
        else:
            return render(request, 'djangoapp/registration.html', context)

# Update the `get_dealerships` view to render the index page with a list of dealerships
def get_dealerships(request):
    context = {}
    if request.method == "GET":
        url = 'https://5b93346d.us-south.apigw.appdomain.cloud/dealerships/dealer-get'
        # Get dealers from the URL
        context = {"dealerships": restapis.get_dealers_from_cf(url)}
        # Concat all dealer's short name
        # Return a list of dealer short name
        return render(request, 'djangoapp/index.html', context)


# Create a `get_dealer_details` view to render the reviews of a dealer
def get_dealer_details(request, dealer_id):
    context = {}
    if request.method == "GET":
        url = 'https://5b93346d.us-south.apigw.appdomain.cloud/reviews/get-review'
        context = {"reviews":  restapis.get_dealer_reviews_by_id_from_cf(url, dealer_id)}
        return render(request, 'djangoapp/dealer_details.html', context)

# Create a `add_review` view to submit a review
def add_review(request, dealer_id):
    if request.method == "GET":
        dealersid = dealer_id
        url = "https://5b93346d.us-south.apigw.appdomain.cloud/dealerships/dealer-get?dealerId={0}".format(dealersid)
        # Get dealers from the URL
        context = {
            "cars": models.CarModel.objects.all(),
            "dealers": restapis.get_dealers_from_cf(url),
        }
        return render(request, 'djangoapp/add_review.html', context)
    if request.method == "POST":
        if request.user.is_authenticated:
            form = request.POST
            review = {
                "name": "{request.user.first_name} {request.user.last_name}",
                "dealership": dealer_id,
                "review": form["content"],
                "purchase": form.get("purchasecheck"),
                }
            if form.get("purchasecheck"):
                review["purchase_date"] = datetime.strptime(form.get("purchasedate"), "%m/%d/%Y").isoformat()
                car = models.CarModel.objects.get(pk=form["car"])
                review["car_make"] = car.carmake.name
                review["car_model"] = car.name
                review["car_year"]= car.year.strftime("%Y")
            json_payload = {"review": review}
            print (json_payload)
            url = "https://5b93346d.us-south.apigw.appdomain.cloud/dealerships/reviews/review-post"
            restapis.post_request(url, json_payload, dealerId=dealer_id)
            return redirect("djangoapp:dealer_details", dealer_id=dealer_id)
        else:
            return redirect("/djangoapp/login")
            

server/djangoapp/templates/djangoapp/about.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            About Us
        </title>
        <meta charset="UTF-8">
        <title>Dealership Review</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    </head>
    <body>
        {% include 'Navbar.html' %}
        <p>
            Welcome to Best Cars dealership, home to the best cars in North America. We sell domestic and imported cars at reasonable prices.
        </p>
    </body>
</html>

server/djangoapp/templates/djangoapp/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>

</head>
    <body>
                       <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Best Cars</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/djangoapp/about">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/djangoapp/contact">Contact Us</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">{{ user.first_name }}{{ user.username }}</a>
                        <a class="btn btn-link" href="logout/">Logout</a>
                    </li>
                    {% else %}
                        <li>
                               <a class="btn btn-link" href="/djangoapp/login/">Sign In</a>
                                <a class="btn btn-link" href="/djangoapp/signup/">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    <!--Add review form here -->
    <main class="container">
    <!--Add review form here -->
    {% for dealer in dealers %}
        <form action="/djangoapp/dealer/{{dealer.id}}/add_review/" method="post">
            {% csrf_token %}
    {% endfor %}
            <div class="form-group">
                <label for="content">Enter the review content:</label>
                <textarea class="form-control" id="content" name="content" rows="2" required></textarea>
            </div>
            <div class="form-group form-check">
                <input class="form-check-input" type="checkbox" name="purchasecheck" id="purchasecheck">
                <label for="purchasecheck">Did you purchase the car? (If yes, kindly fill the below information as well. If no, You can just submit the form.)</label>
            </div>
            <div class="form-group">
                <label for="car">Select your car (model-make-year):</label>
                <select name="car" id="car" class="form-select">
                    {% for car in cars %}
                        <option selected value={{car.id}}>{{car.name}}-{{car.car_make.name}}-{{ car.year|date:"Y" }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group" data-provide="datepicker">
                <label for="purchasedate">Select your purchase date:</label>
                <input class="form-control" type="text" name="purchasedate" id="purchasedate">
            </div>
           <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </main>
    </body>
</html>

server/djangoapp/templates/djangoapp/contact.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Contact Us
        </title>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
        <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    </head>
    <body>
        {% include 'Navbar.html' %}
        <div class="container">
            <p class="heading-txt" style="font-size: 2em; margin-bottom: 3%; text-align: center;">Contact</p>
            <div style="margin-top: 5%;display: flex; justify-content: space-evenly; flex-wrap: wrap;">
            <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Contact Information</div>
                <div class="card-body">
                    <h5 class="card-title">Customer Care</h5>
                    <p class="card-text">Name: Dale </br> Mobile: 12145623 </br> Email: Dale@dealership.com </p>
                </div>
            </div>
                    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Contact Information</div>
                <div class="card-body">
                    <h5 class="card-title">Customer Care</h5>
                    <p class="card-text">Name: Dale </br> Mobile: 12145623 </br> Email: Dale@dealership.com </p>
                </div>
            </div>
                    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Contact Information</div>
                <div class="card-body">
                    <h5 class="card-title">Customer Care</h5>
                    <p class="card-text">Name: Dale </br> Mobile: 12145623 </br> Email: Dale@dealership.com </p>
                </div>
            </div>
                    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Contact Information</div>
                <div class="card-body">
                    <h5 class="card-title">Customer Care</h5>
                    <p class="card-text">Name: Dale </br> Mobile: 12145623 </br> Email: Dale@dealership.com </p>
                </div>
            </div>
                    <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
                <div class="card-header">Contact Information</div>
                <div class="card-body">
                    <h5 class="card-title">Customer Care</h5>
                    <p class="card-text">Name: Dale </br> Mobile: 12145623 </br> Email: Dale@dealership.com </p>
                </div>
            </div>
            </div>
        </div>
    </body>
</html>

server/djangoapp/templates/djangoapp/dealer_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dealership Review</title>
    {% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

    <body>

    <!--Add a nav bar here -->

    <!-- Add reviews as cards -->

    </body>

</html>

server/djangoapp/templates/djangoapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projeto Avaliação da Concessionária</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>

</head>

    <body>
        {% include 'Navbar.html' %}
    <!--Add a nav bar here -->
    <div class="container">
     <table class="table table-striped" id="table" data-filter-control="true" style="margin-top: 3%; margin-bottom: 3%;">
        <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Dealer Name</th>
                    <th scope="col">City</th>
                    <th scope="col">Address</th>
                    <th scope="col">Zip</th>
                    <th data-field="state" data-filter-control="select">State</th>
                </tr>
            </thead>
        <tbody>
            {% for dealer in dealerships%}
                <tr>
                    <td style="padding: 2%;">{{dealer.id}}</td>
                    <td style="padding: 2%;"><a href="{% url 'djangoapp:dealer_details' dealer.id %}">{{dealer.full_name}}</a></td>
                    <td style="padding: 2%;">{{dealer.city}}</td>
                    <td style="padding: 2%;">{{dealer.address}}</td>
                    <td style="padding: 2%;">{{dealer.zip}}</td>
                    <td style="padding: 2%;">{{dealer.st}}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <!--Add a dealer table here -->
    </div>

    </body>
    <script>
        $(function() {
            $('#table').bootstrapTable()
        })
    </script>

</html>

server/djangoapp/templates/djangoapp/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
    <body>
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Best Cars</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/djangoapp/about">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/djangoapp/contact">Contact Us</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">{{ user.first_name }}{{ user.username }}</a>
                        <a class="btn btn-link" href="logout/">Logout</a>
                    </li>
                    {% else %}
                        <li>
                                <a class="btn btn-link" href="/djangoapp/login/">Sign In</a>
                                <a class="btn btn-link" href="/djangoapp/signup/">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <form action="{% url 'djangoapp:registration' %}" method="post">
            <div class="container">
                <h1>Sign Up</h1>
                <hr>
                <label for="username"><b>User Name</b></label>
                <input type="text" placeholder="Enter User Name: " name="username" required>
                <label for="firstname"><b>First Name</b></label>
                <input type="text" placeholder="Enter First Name: " name="firstname" required>
                <label for="lastname"><b>Last Name</b></label>
                <input type="text" placeholder="Enter Last Name: " name="lastname" required>
                <label for="psw"><b>Password</b></label>
                <input type="password" placeholder="Enter Password: " name="psw" required>
                <div>
                    {% csrf_token %}
                    <button class="button" type="submit">Sign Up</button>
                </div>
            </div>
        </form>
    </body>
</html>

server/djangoapp/templates/djangoapp/user_login.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Login
        </title>
        <meta charset="UTF-8">
    <title>Dealership Review</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.2/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
    </head>
    <body>
                    <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Best Cars</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/djangoapp/about">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/djangoapp/contact">Contact Us</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li>
                        <a class="btn btn-link" href="#">{{ user.first_name }}{{ user.username }}</a>
                        <a class="btn btn-link" href="logout/">Logout</a>
                    </li>
                    {% else %}
                        <li>
                                <a class="btn btn-link" href="/djangoapp/login/">Sign In</a>
                                <a class="btn btn-link" href="/djangoapp/signup/">Sign Up</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container" style=" text-align: center;">
            <h1>Login</h1>
            <form action="{% url 'djangoapp:login' %}"  method="post" style="margin-top: 5%;">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label" style="font-size: 1.5em; font-weight: normal;">User Name</label> <br />
                    <input type="text" placeholder="Enter User Name: " name="username" style="width: 50%; border-radius: 7px;" required>
                </div>
                <div class="mb-3">
                    <label for="exampleInputPassword1" class="form-label" style="font-size: 1.5em;">Password</label> <br />
                    <input type="password" placeholder="Enter Password: " style="width: 50%; border-radius: 7px;" name="psw" required>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </body>
</html>